name: .NET Core

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.101
    - name: Build with dotnet
      run: dotnet build --configuration Release --output dist
    - name: Archive build results
      uses: actions/upload-artifact@v1
      with:
        name: Build-Result
        path: dist

  test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
    - name: Run tests with dotnet
      run: dotnet test --configuration Release --logger trx --results-directory TestResults
    - name: Archive test results
      uses: actions/upload-artifact@v1
      with:
        name: Test-Results
        path: TestResults
        
  publish:  
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
    - name: Package application with dotnet
      run: dotnet publish --configuration Release --output dist
    - name: Archive published app 
      uses: actions/upload-artifact@v1
      with:
        name: Published-App
        path: dist

  package-nuget:
    name: Package NuGet library ${{ matrix.project }}
    runs-on: [ubuntu-latest]
    strategy:
      matrix:
        project: ['Emby.Naming', 'MediaBrowser.Common', 'MediaBrowser.Controller', 'MediaBrowser.Model']
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
    - name: Setup NuGet
      uses: nuget/setup-nuget@v1
      with:
        nuget-api-key: ${{ secrets.GITHUB_TOKEN }}
        nuget-api-key-source: https://nuget.pkg.github.com/mark-monteiro/index.json
        nuget-version: latest 
    - name: Package Project
      run: dotnet pack ${{matrix.project}} --configuration Release --output dist --version-suffix build.${{github.run_number}}
    - name: Publish NuGet Package
      run: dotnet nuget push dist/*.nupkg --source https://nuget.pkg.github.com/mark-monteiro/index.json
